### ISSUE TITLE
Show operation in demo 

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-view-utilities#19] opened 2019-09-04 11:08 UTC
There is a problem in the demo of show operation. I think it isn't related with the show operation itself, but we are missing some elements to show again in the demo.  
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/22586369/64249832-4deeaf00-cf1d-11e9-9aa2-bb495d019ef0.gif)

**Comment by ugurdogrusoz** [comment] 2019-09-04 11:16
Looks like the problem is the following: when we select n19 and try showing its hidden neighbors, it will not work and Show all won't work here either to show its 2 incident hidden edges.

**Comment by ugurdogrusoz** [comment] 2019-09-04 11:50
Could be related to https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/issues/7

**Comment by ugurdogrusoz** [comment] 2019-09-05 12:10
@hasanbalci Please verify and close if OK

**Comment by hasanbalci** [comment] 2019-09-06 09:28
In the demo file, if we select n1 (compound node) and hide it, then selecting n5 and clicking on "Show Hidden Neighbors of Selected" doesn't show the neighbors of n5.

**Comment by ugurdogrusoz** [comment] 2019-09-06 10:30
@hasanbalci This is probably due to use a core Cytoscape function that doesn't support compounds. @nasimsaleh Could your confirm?

**Comment by nasimsaleh** [comment] 2019-09-06 13:23
@ugurdogrusoz  the compound node is removed, plus the undo redo functionality for the new api function "showHiddenNeighbors" is added

**Comment by ugurdogrusoz** [comment] 2019-09-06 15:04
Undoable demo throws an exception saying showHiddenNeighbors does not exist as a function?

**Comment by ugurdogrusoz** [comment] 2019-09-06 15:05
Can we also synch up the undoable and non-undoable demos (by at least adding a title to the page for undoable demo)?

**Comment by nasimsaleh** [comment] 2019-09-06 20:32
@ugurdogrusoz Can you refresh the page? I don't get an exception. Ok i will add titles

**Comment by ugurdogrusoz** [comment] 2019-09-07 09:46
@nasimsaleh Sorry, you're right when refreshed it worked. And I see titles being synched, thanks, closing now.

**Closed as completed by ugurdogrusoz** 2019-09-07 09:46 UTC
Labels: bug
